### PR TITLE
Finnish

### PR DESCRIPTION
**Pull request by heidiwenger**
Finnish translation.

### CODE REVIEW

**Comment by heidiwenger** [comment]
I hope i was doing this right.

**Comment by xfangfang** [comment]
Thanks for your translation.
However, you should not directly modify the original Chinese translation, but create a new folder to store the Finnish translation.

I think the translation file path should be: Macast/i18n/fi/LC_MESSAGES/macast.po

**Comment by xfangfang** [comment]
> I think the translation file path should be: Macast/i18n/fi/LC_MESSAGES/macast.po

or Macast/i18n/fi_FI/LC_MESSAGES/macast.po

**Comment by xfangfang** [comment]
> Ok, i can see create a new file, but how do i create a new folder?

just input the path as the file name

the path should be Macast/i18n/fi/LC_MESSAGES/macast.po

**Comment by xfangfang** [comment]
sorry for my English.

1. open this link: https://github.com/xfangfang/Macast/tree/main/i18n
2. click `add file` - `create new file`
3. input `fi/LC_MESSAGES/macast.po` as the file name

**Pull request closed without merging**
